force-app/main/default/objects/ViewNotification__e/ViewNotification__e.object-meta.xml
<CustomObject>
    <label>ViewNotification</label>
    <pluralLabel>ViewNotifications</pluralLabel>
</CustomObject>

force-app/main/default/objects/ViewNotification__e/fields/EventType__c.field-meta.xml
<CustomField>
    <fullName>EventType__c</fullName>
    <description>join：表示中に遷移
leave：非表示に遷移</description>
    <label>イベントタイプ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ViewNotification__e/fields/ObjectName__c.field-meta.xml
<CustomField>
    <fullName>ObjectName__c</fullName>
    <label>オブジェクト名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ViewNotification__e/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <label>レコードID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ViewNotification__e/fields/SmallPhotoUrl__c.field-meta.xml
<CustomField>
    <fullName>SmallPhotoUrl__c</fullName>
    <label>SmallPhotoUrl</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ViewNotification__e/fields/ViewDateTime__c.field-meta.xml
<CustomField>
    <fullName>ViewDateTime__c</fullName>
    <label>表示時刻</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ViewNotification__e/fields/ViewUserId__c.field-meta.xml
<CustomField>
    <fullName>ViewUserId__c</fullName>
    <label>表示中ユーザID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ViewNotification__e/fields/ViewUserName__c.field-meta.xml
<CustomField>
    <fullName>ViewUserName__c</fullName>
    <label>表示中ユーザ氏名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ViewNotificationController.cls
/**
 * @description       :
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             :
 * @last modified on  : 11-05-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 **/
public with sharing class ViewNotificationController {

  @AuraEnabled(cacheable=true)
  public static User getUserData() {
    System.debug('Call getUserData');
    return [
      SELECT Id, Name, SmallPhotoUrl
      FROM User
      WHERE Id = :UserInfo.getUserId()
    ];
  }

  @AuraEnabled(cacheable=true)
  public static User getUserDataById(string UserId) {
    return [SELECT Id, Name, SmallPhotoUrl FROM User WHERE Id = :UserId];
  }

  @AuraEnabled
  public static void publish(String recordId, String eventType) {
    Id id = recordId;
    DescribeSObjectResult describe = id.getSobjectType().getDescribe();

    User u = getUserData();

    List<ViewNotification__e> notifications = new List<ViewNotification__e>();
    notifications.add(
      new ViewNotification__e(
        ObjectName__c = describe.getName(),
        RecordId__c = recordId,
        ViewDateTime__c = DateTime.now().format('yyyy/MM/dd HH:mm', 'JST'),
        viewUserId__c = UserInfo.getUserId(),
        viewUserName__c = UserInfo.getName(),
        eventType__c = eventType,
        SmallPhotoUrl__c = u.SmallPhotoUrl
      )
    );
System.debug('notifications:' + notifications);

    List<Database.SaveResult> results = EventBus.publish(notifications);
    for (Database.SaveResult sr : results) {
      if (sr.isSuccess()) {
        // System.debug('Successfully published event.');
      } else {
        for (Database.Error err : sr.getErrors()) {
          System.debug(
            'Error returned: ' +
            err.getStatusCode() +
            ' - ' +
            err.getMessage()
          );
        }
      }
    }
  }
}